server:
  port: 8091
  

spring:
  application:
    name: Config-Server
   
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Surya1231998/Config-Server-for-Microservices
          clone-on-start: true
 
  